# Generated by Django 5.1.6 on 2025-03-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectmanager'),
        ),
    ]
